# Generated by Django 2.0.7 on 2018-08-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180812_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studmks',
            name='UID',
            field=models.IntegerField(default=0),
        ),
    ]
