# Generated by Django 2.0.7 on 2018-08-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180806_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='UID',
            field=models.IntegerField(default=0),
        ),
    ]
