# Generated by Django 2.0.7 on 2018-08-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180812_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studmks',
            name='UID',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
