# Generated by Django 2.0.7 on 2018-08-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180812_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='studmks',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
    ]
