# Generated by Django 2.0.7 on 2018-08-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180808_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='eligible',
        ),
    ]
